In [5]:
import pandas as pd

data=pd.read_csv("LargeTrain.csv")
data.shape

(10868, 1805)

In [6]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.ensemble import ExtraTreesClassifier

# Build a classification task
X, y = make_classification(n_samples=10868,
                           n_features=1805,
                           n_informative=42,
                           n_redundant=0,
                           n_repeated=0,
                           n_classes=2,
                           n_clusters_per_class=1,
                           random_state=0,
                           shuffle=False)

# Build a forest and compute the feature importances
forest = ExtraTreesClassifier(n_estimators=250,
                              random_state=0)

forest.fit(X, y)
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(X.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

# Plot the feature importances of the forest
plt.figure()
plt.title("Feature importances")
plt.bar(range(X.shape[1]), importances[indices],
       color="r", yerr=std[indices], align="center")
plt.xticks(range(X.shape[1]), indices)
plt.xlim([-1, X.shape[1]])
plt.show()

,Virtual,Offset,loc,Import,Imports,var,Forwarder,UINT,LONG,BOOL,...,Img99,Img100,Img101,Img102,Img103,Img104,Img105,Img106,Img107,Class
0,3,3,689,18,6,890,6,39,17,88,...,35148.0,8687.0,55835.0,9078.0,21355.0,56302.0,10380.0,171979.0,162674.0,2
1,3,3,583,15,5,1574,5,6,7,30,...,571.0,718.0,1762.0,642.0,1820.0,1675.0,1100.0,7702.0,6551.0,8
2,3,4,2796,15,5,625,5,58,11,152,...,29872.0,16910.0,31708.0,9000.0,17586.0,30719.0,30062.0,55331.0,12946.0,9
3,3,3,373,27,9,615,9,16,10,34,...,10742.0,9755.0,26992.0,9069.0,24885.0,27108.0,13219.0,122247.0,98621.0,9
4,3,3,77,12,4,66,4,3,0,5,...,962.0,1307.0,3119.0,1172.0,3522.0,3245.0,2001.0,15501.0,11864.0,1
5,3,3,86,6,2,6,2,0,0,1,...,474.0,561.0,1389.0,581.0,1537.0,1293.0,1275.0,7048.0,6164.0,6
6,3,3,469,21,7,291,7,43,15,82,...,33452.0,15370.0,63663.0,15581.0,42067.0,63996.0,21127.0,221716.0,176170.0,2
7,3,3,2090,21,7,4035,7,17,8,40,...,1378.0,1901.0,4588.0,2004.0,5550.0,4494.0,2803.0,21692.0,18786.0,2
8,3,3,691,18,6,597,6,30,16,61,...,43370.0,13748.0,66715.0,14946.0,39350.0,71793.0,18663.0,219223.0,167493.0,2
9,6,6,229,0,8,526,0,11,1,13,...,1031.0,1076.0,3040.0,1097.0,3216.0,2985.0,1577.0,12860.0,6860.0,6